### ISSUE TITLE
変数名の統一

### ISSUE THREAD

**Issue by sakakazu2468** [c0119177/ProjExD#21]
https://github.com/c0119177/ProjExD/blob/9d3bb3d9af69d0a8f68c68f2b3240affbd2fbc31/ex06/jump_kokaton.py#L30
textとtxtが混ざっているので、どちらかに統一しましょう！

**Comment by c0119177** [comment]
https://github.com/c0119177/ProjExD/commit/79fe8d5abb86e878ce14fac1a410d61298e0cacc
まとめて修正しました。 #22
