### ISSUE TITLE
2回目の同処理

### ISSUE THREAD

**Issue by 10BIT-okinawa** [c0119177/ProjExD#23]
https://github.com/c0119177/ProjExD/blob/9d3bb3d9af69d0a8f68c68f2b3240affbd2fbc31/ex06/jump_kokaton.py#L26
23行目と同じ処理をしているので不要ではないでしょうか？
textの処理の区切りで改行を入れるとより良いと思います

**Comment by c0119177** [comment]
https://github.com/c0119177/ProjExD/commit/79fe8d5abb86e878ce14fac1a410d61298e0cacc
まとめて修正しました。 #22
